/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package happyjuicyshop;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {
    public String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String userEmail) {
        initComponents();
        email = userEmail;
        if(!email.equals("admin@gmail.com"))
        {
            btnManaCate.setVisible(false);
            btnNewProduct.setVisible(false);
            btnVEDProduct.setVisible(false);
            btnVerifyU.setVisible(false);
            btnDailyRevenue.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnPOrder = new javax.swing.JButton();
        btnViewBO = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnChangeSecQ = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnManaCate = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        btnVEDProduct = new javax.swing.JButton();
        btnVerifyU = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDailyRevenue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logoutt.png"))); // NOI18N
        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        btnPOrder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tea.png"))); // NOI18N
        btnPOrder.setText("Place Order");
        btnPOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, -1, -1));

        btnViewBO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewBO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        btnViewBO.setText("View Bill & Order Placed Details");
        btnViewBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBOActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBO, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, -1, -1));

        btnChangePass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ChangePass.png"))); // NOI18N
        btnChangePass.setText("Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, -1, -1));

        btnChangeSecQ.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnChangeSecQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        btnChangeSecQ.setText("Change Securtiy Question");
        btnChangeSecQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSecQActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeSecQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 390, -1));

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitbig.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, -1, -1));

        btnManaCate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManaCate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cacategory.png"))); // NOI18N
        btnManaCate.setText("Manage Category");
        btnManaCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManaCateActionPerformed(evt);
            }
        });
        getContentPane().add(btnManaCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, -1, -1));

        btnNewProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpro.png"))); // NOI18N
        btnNewProduct.setText("New Product");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, -1, -1));

        btnVEDProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnVEDProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        btnVEDProduct.setText("View, Edit & Delete Product");
        btnVEDProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVEDProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnVEDProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, -1, -1));

        btnVerifyU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnVerifyU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Verify.png"))); // NOI18N
        btnVerifyU.setText("Verify Users");
        btnVerifyU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyUActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerifyU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnDailyRevenue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDailyRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revenue-30.png"))); // NOI18N
        btnDailyRevenue.setText("Daily Revenue");
        btnDailyRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyRevenueActionPerformed(evt);
            }
        });
        getContentPane().add(btnDailyRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         int a =JOptionPane.showConfirmDialog(null,"Do you really wanna Log Out","Select",JOptionPane.YES_NO_OPTION);
         if(a==0){
         setVisible(false);
         new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         int a =JOptionPane.showConfirmDialog(null,"Do you really wanna Close Application","Select",JOptionPane.YES_NO_OPTION);
         if(a==0){
         System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnManaCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManaCateActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_btnManaCateActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        // TODO add your handling code here:
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnVEDProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVEDProductActionPerformed
        // TODO add your handling code here:
        new ViewEditDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnVEDProductActionPerformed

    private void btnVerifyUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyUActionPerformed
        // TODO add your handling code here:
        new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_btnVerifyUActionPerformed

    private void btnPOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOrderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder(email).setVisible(true);
    }//GEN-LAST:event_btnPOrderActionPerformed

    private void btnViewBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBOActionPerformed
        // TODO add your handling code here:
        new ViewBillsOrderDetails().setVisible(true);
    }//GEN-LAST:event_btnViewBOActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        new ChangePassword(email).setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnChangeSecQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeSecQActionPerformed
        // TODO add your handling code here:     
        new ChangeSecurityQuestion(email).setVisible(true);
    }//GEN-LAST:event_btnChangeSecQActionPerformed

    private void btnDailyRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyRevenueActionPerformed
        // TODO add your handling code here:
        new DailyRevenue().setVisible(true);
    }//GEN-LAST:event_btnDailyRevenueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnChangeSecQ;
    private javax.swing.JButton btnDailyRevenue;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManaCate;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnPOrder;
    private javax.swing.JButton btnVEDProduct;
    private javax.swing.JButton btnVerifyU;
    private javax.swing.JButton btnViewBO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
